---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: network
  connection: local
  gather_facts: false

  tasks:

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d"
      register: tstamp
      delegate_to: localhost
    
    - name: Connect remote network devices
      cli_command:
        command: sh int desc
      register: output
      ignore_errors: yes

    - name: Debug commands
      debug:
        msg: "{{output.stdout_lines}}"
    
